# -*- coding: utf-8 -*-
"""AnálisisMonterrey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8N5E_tWOPQj4I6REycKNH5RaxyomNrU

## Cargar los datos
"""

from google.colab import drive
drive.mount('/content/drive')

folder_path = "/content/drive/My Drive/FutbolStats/"

# Importar librerias
import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import cross_val_score, KFold

# Leer base de datos
ruta = "/content/drive/My Drive/FutbolStats/"
liga_mx = pd.read_csv(ruta + "liga_mx.csv")

liga_mx.head(20)

liga_mx = pd.DataFrame(liga_mx)

monterrey = liga_mx[(liga_mx["home_team"]== "Monterrey") | (liga_mx["away_team"]== "Monterrey")]

# Crea una nueva columna llamada 'monterrey_win' e inicialízala en 0
monterrey['monterrey_win'] = 0

# Establece la columna en 1 para las victorias de Monterrey como equipo local
monterrey.loc[(monterrey['home_team'] == 'Monterrey') & (monterrey['home_win'] == True), 'monterrey_win'] = 1

# Establece la columna en 1 para las victorias de Monterrey como equipo visitante
monterrey.loc[(monterrey['away_team'] == 'Monterrey') & (monterrey['away_win'] == True), 'monterrey_win'] = 1

monterrey.drop(columns=["timezone", "venue_city", "date", "venue_id"], inplace=True)

monterrey.set_index('id', inplace=True)
monterrey["season"] = monterrey["season"].astype(str)
monterrey.tail(10)

monterrey.head(10)

"""## Exploración de datos"""

monterrey.shape

monterrey.dtypes

monterrey.info()

"""### Exploración Variables Cuantitativas"""

monterrey.describe()

mediana_homeg = round(monterrey["home_goals"].median(),2)
moda_homeg= round(monterrey["home_goals"].mode(),2)
rango_homeg = round(monterrey["home_goals"].max()- monterrey["home_goals"].min(),2)
var_homeg = round(monterrey["home_goals"].var(),2)
std_homeg = round(monterrey["home_goals"].std(),2)

print("Mediana Total de Goles en Casa:",mediana_homeg)
print("Moda Total de Goles en Casa:",moda_homeg)
print("Rango Total de Goles en Casa:",rango_homeg)
print("Varianza Total de Goles en Casa:",var_homeg)
print("Desviación estándar Total de Goles en Casa:",std_homeg)
print("\n")

mediana_awayg = round(monterrey["away_goals"].median(),2)
moda_awayg= round(monterrey["away_goals"].mode(),2)
rango_awayg = round(monterrey["away_goals"].max()- monterrey["away_goals"].min(),2)
var_awayg = round(monterrey["away_goals"].var(),2)
std_awayg = round(monterrey["away_goals"].std(),2)

print("Mediana Total de Goles Fuera de Casa:",mediana_awayg)
print("Moda Total de Goles Fuera de  Casa:",moda_awayg)
print("Rango Total de Goles Fuera de  Casa:",rango_awayg)
print("Varianza Total de Goles Fuera de  Casa:",var_awayg)
print("Desviación estándar Total de Goles Fuera de  Casa:",std_awayg)

variables_cuant = ["home_goals",	"away_goals",	"home_goals_half_time",	"away_goals_half_time",	"home_goals_fulltime"	,"away_goals_fulltime",	"home_goals_extra_time",	"away_goals_extratime",	"home_goals_penalty",	"away_goals_penalty"]
monterrey_subset = monterrey[variables_cuant]

Q1 = monterrey_subset.quantile(0.25)
Q2 = monterrey_subset.median()
Q3 = monterrey_subset.quantile(0.75)
IQR = Q3 - Q1
outliers = ((monterrey_subset < (Q1 - 1.5 * IQR)) | (monterrey_subset > (Q3 + 1.5 * IQR)))
print(f"Cuartiles:\n{pd.DataFrame({'Q1': Q1, 'Mediana': Q2, 'Q3': Q3, 'IQR': IQR})}")
print(f"\nNúmero de outliers por variable:\n{outliers.sum()}")

plt.figure(figsize=(20, 20))
for i, col in enumerate(monterrey_subset.columns, 1):
    plt.subplot(5, 5, i)
    sns.boxplot(y=monterrey_subset[col])
    plt.title(f"Boxplot de {col}")
plt.tight_layout()
plt.show()

monterrey_subset.hist(figsize=(20, 20), bins=20, grid=False)
plt.suptitle("Histogramas de las Variables", fontsize=14)
plt.show()

skewness = monterrey_subset.skew()
print(f"\nCoeficiente de Asimetría (Skewness):\n{skewness}")

plt.figure(figsize=(10, 10))
sns.heatmap(monterrey_subset.corr(), annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
plt.title("Mapa de Calor - Correlación de Variables ")
plt.show()

"""### Exploración Variables Cualitativas"""

tabla_dist_frecuencia = monterrey["referee"].value_counts().reset_index()
tabla_dist_frecuencia.columns = ["Referee", "Frecuencia"]
tabla_dist_frecuencia["Frecuencia Relativa (%)"] = (tabla_dist_frecuencia["Frecuencia"] / tabla_dist_frecuencia["Frecuencia"].sum()) * 100
print(f"Tabla de distribución de Frecuencias: \n{tabla_dist_frecuencia}")

tabla_dist_frecuencia = monterrey["venue_name"].value_counts().reset_index()
tabla_dist_frecuencia.columns = ["Venue", "Frecuencia"]
tabla_dist_frecuencia["Frecuencia Relativa (%)"] = (tabla_dist_frecuencia["Frecuencia"] / tabla_dist_frecuencia["Frecuencia"].sum()) * 100
print(f"Tabla de distribución de Frecuencias: \n{tabla_dist_frecuencia}")

tabla_dist_frecuencia = monterrey["season"].value_counts().reset_index()
tabla_dist_frecuencia.columns = ["Temporada", "Frecuencia"]
tabla_dist_frecuencia["Frecuencia Relativa (%)"] = (tabla_dist_frecuencia["Frecuencia"] / tabla_dist_frecuencia["Frecuencia"].sum()) * 100
print(f"Tabla de distribución de Frecuencias: \n{tabla_dist_frecuencia}")

tabla_dist_frecuencia = monterrey["round"].value_counts().reset_index()
tabla_dist_frecuencia.columns = ["Ronda", "Frecuencia"]
tabla_dist_frecuencia["Frecuencia Relativa (%)"] = (tabla_dist_frecuencia["Frecuencia"] / tabla_dist_frecuencia["Frecuencia"].sum()) * 100
print(f"Tabla de distribución de Frecuencias: \n{tabla_dist_frecuencia}")

tabla_dist_frecuencia = monterrey["home_team"].value_counts().reset_index()
tabla_dist_frecuencia.columns = ["Equipo local", "Frecuencia"]
tabla_dist_frecuencia["Frecuencia Relativa (%)"] = (tabla_dist_frecuencia["Frecuencia"] / tabla_dist_frecuencia["Frecuencia"].sum()) * 100
print(f"Tabla de distribución de Frecuencias: \n{tabla_dist_frecuencia}")

tabla_dist_frecuencia = monterrey["away_team"].value_counts().reset_index()
tabla_dist_frecuencia.columns = ["Equipo Visitante", "Frecuencia"]
tabla_dist_frecuencia["Frecuencia Relativa (%)"] = (tabla_dist_frecuencia["Frecuencia"] / tabla_dist_frecuencia["Frecuencia"].sum()) * 100
print(f"Tabla de distribución de Frecuencias: \n{tabla_dist_frecuencia}")

frecuencia = monterrey['monterrey_win'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(frecuencia.values, labels=frecuencia.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribución de Victorias y Derrotas del Monterrey')
plt.axis('equal')
plt.show()

frecuencia = monterrey['referee'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(frecuencia.values, labels=frecuencia.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribución de Referees')
plt.axis('equal')
plt.show()

frecuencia = monterrey['venue_name'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(frecuencia.values, labels=frecuencia.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribución de Venue')
plt.axis('equal')
plt.show()

frecuencia = monterrey['season'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(frecuencia.values, labels=frecuencia.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribución de Temporada')
plt.axis('equal')
plt.show()

frecuencia = monterrey['home_team'].value_counts()
plt.figure(figsize=(20, 20))
plt.pie(frecuencia.values, labels=frecuencia.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribución de Local')
plt.axis('equal')
plt.show()

frecuencia = monterrey['away_team'].value_counts()
plt.figure(figsize=(20, 20))
plt.pie(frecuencia.values, labels=frecuencia.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribución de Visitante')
plt.axis('equal')
plt.show()

"""## Limpieza de los datos"""

monterrey.isnull().sum()

monterrey["home_win"] = monterrey["home_win"].fillna("False")
monterrey["away_win"] = monterrey["away_win"].fillna("False")
monterrey["home_goals"] = monterrey["home_goals"].fillna(0)
monterrey["away_goals"] = monterrey["away_goals"].fillna(0)
monterrey["home_goals_half_time"] = monterrey["home_goals_half_time"].fillna(0)
monterrey["away_goals_half_time"] = monterrey["away_goals_half_time"].fillna(0)
monterrey["home_goals_fulltime"] = monterrey["home_goals_fulltime"].fillna(0)
monterrey["away_goals_fulltime"] = monterrey["away_goals_fulltime"].fillna(0)
monterrey["home_goals_extra_time"] = monterrey["home_goals_extra_time"].fillna(0)
monterrey["away_goals_extratime"] = monterrey["away_goals_extratime"].fillna(0)
monterrey["home_goals_penalty"] = monterrey["home_goals_penalty"].fillna(0)
monterrey["away_goals_penalty"] = monterrey["away_goals_penalty"].fillna(0)
monterrey["referee"] = monterrey["referee"].fillna("César Ramos Palazuelos, Mexico")

monterrey.isnull().sum()

# Diccionario manual de mapeo de nombres
mapping = {
    "L. Santander": "Luis Santander, Mexico",
    "C. Ramos": "César Ramos Palazuelos, Mexico",
    "Cesar Arturo Ramos Palazuelos, Mexico": "César Ramos Palazuelos, Mexico",
    "F. Guerrero":"Fernando Guerrero Ramirez, Mexico",
    "M. Ortíz": "Marco Antonio Ortiz Nava, Mexico",
    "Ó. Mejía": "Oscar Mejia Garcia, Mexico",
    "D. Montaño": "Diego Montano, Mexico",
    "F. Hernández": "Fernando Hernandez, Mexico",
    "J. Rojas":"Jorge Isaac Rojas Castillo, Mexico",
    "V. Cáceres": "Victor Alfonso Caceres Hernandez, Mexico",
    "E. Miranda": "Erick Yair Miranda Galindo, Mexico",
    "Ó. Macías": "Oscar Macias, Mexico",
    "J. Pérez": "Jorge Antonio Perez Duran, Mexico",
    "D. Quintero": "Daniel Quintero Huitron, Mexico",
    "E. Galván": "Eduardo Galvan Basulto, Mexico",
    "A. Escobedo": "Adonai Escobedo Gonzalez, Mexico",
    "I. Lopez": "Ismael Rosario Lopez Penuelas, Mexico",
    "J. Lopez": "Jesus Rafael Lopez Valle, Mexico",
    "E. Morales": "Edgar Allan Morales Olvera, Mexico",
    "A. Maganda": "dalid Maganda Villalva, Mexico",
    "J. Peñaloza": "Jose Penaloza, Mexico"

}

# Reemplazar los nombres en el DataFrame
monterrey["referee"] = monterrey["referee"].replace(mapping)

tabla_dist_frecuencia = monterrey["referee"].value_counts().reset_index()
tabla_dist_frecuencia.columns = ["Referee", "Frecuencia"]
tabla_dist_frecuencia["Frecuencia Relativa (%)"] = (tabla_dist_frecuencia["Frecuencia"] / tabla_dist_frecuencia["Frecuencia"].sum()) * 100
print(f"Tabla de distribución de Frecuencias: \n{tabla_dist_frecuencia}")

# Diccionario manual de mapeo de nombres
map = {
    "Estadio BBVA": "Estadio BBVA Bancomer",
    "Estadio BBVA Bancomer (Guadalupe)": "Estadio BBVA Bancomer",
    "Estadio Azteca (Ciudad de México (D.F.))":"Estadio Azteca",
    "Estadio Caliente (Tijuana)":"Estadio Caliente",
    "Estadio Jalisco (Guadalajara)": "Estadio Jalisco",
    "Estadio AKRON (Zapopan)": "Estadio AKRON",
    "Estadio Universitario de Nuevo León":"Estadio Universitario (UANL)",
    "Estadio Universitario":"Estadio Universitario (UANL)",
    "Estadio Universitario de Nuevo León (San Nicolás de los Garza)": "Estadio Universitario (UANL)",
    "Estadio Olímpico de Universitario": "Estadio Olimpico Universitario",
    "Estadio Leon": "Estadio León",
    "Estadio Cuauhtemoc": "Estadio Cuauhtémoc",
    "Estadio AKRON": "Estadio Akron",
    "Estadio Nemesio Diez":"Estadio Nemesio Díez",
    "Estadio Nuevo Corona":"Estadio TSM Corona",
    "Estadio Corona": "Estadio TSM Corona",
    "Estadio Nuevo Corona (Torreón)": "Estadio TSM Corona",
    "Estadio Miguel Hidalgo": "Estadio Hidalgo",
    "Estadio Nemesio Díez (Toluca de Lerdo)": "Estadio Nemesio Díez",
    "Estadio Corregidora": "Estadio La Corregidora",
    "Estadio Hidalgo (Pachuca de Soto)": "Estadio Hidalgo",
    "Estadio Victoria de Aguascalientes (Aguascalientes)":"Estadio Victoria",
    "Estadio Olímpico Universitario": "Estadio Olimpico Universitario",
    "Estadio Luis de la Fuente (Veracruz)":"Estadio Luis Pirata Fuente",
    "Estadio El Encanto": "Estadio de Mazatlán",
    "Estadio Ciudad de los Deportes": "Estadio Azul",
    "Estadio Generalísimo José María Morelos y Pavón": "Estadio Jose Maria Morelos y Pavon",
    "Estadio Victoria": "Estadio Victoria de Aguascalientes",
    "Estadio Generalísimo José María Morelos y Pavón (Morelia)": "Estadio Jose Maria Morelos y Pavon",
    "Estadio AKRON":"Estadio Akron"

}

# Reemplazar los nombres en el DataFrame
monterrey["venue_name"] = monterrey["venue_name"].replace(map)

tabla_dist_frecuencia = monterrey["venue_name"].value_counts().reset_index()
tabla_dist_frecuencia.columns = ["Venue", "Frecuencia"]
tabla_dist_frecuencia["Frecuencia Relativa (%)"] = (tabla_dist_frecuencia["Frecuencia"] / tabla_dist_frecuencia["Frecuencia"].sum()) * 100
print(f"Tabla de distribución de Frecuencias: \n{tabla_dist_frecuencia}")

frecuencia = monterrey['venue_name'].value_counts()
plt.figure(figsize=(22, 22))
plt.pie(frecuencia.values, labels=frecuencia.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribución de Venue')
plt.axis('equal')
plt.show()

monterrey

monterrey.info()

"""## Transformación de datos"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Copia del dataset
df = monterrey.copy()

# Label Encoding para referee, venue_name, home_team, away_team y round
label_enc = LabelEncoder()
df["referee"] = label_enc.fit_transform(df["referee"])
df["venue_name"] = label_enc.fit_transform(df["venue_name"])
df["round"] = label_enc.fit_transform(df["round"])
df["home_team"] = label_enc.fit_transform(df["home_team"])
df["away_team"] = label_enc.fit_transform(df["away_team"])


# One-Hot Encoding para 'season' (porque tiene pocas categorías)
df = pd.get_dummies(df, columns=["season"], drop_first=True)

# Asegurar que las columnas son binaria
df["monterrey_win"] = df["monterrey_win"].astype(int)
df[["home_win", "away_win"]] = df[["home_win", "away_win"]].replace({'True': True, 'False': False}).astype(int)

# Asegurar que las columnas son binaria
df[["season_2017", "season_2018", "season_2019", "season_2020", "season_2021", "season_2022", "season_2023", "season_2024"]] = df[["season_2017", "season_2018", "season_2019", "season_2020", "season_2021", "season_2022", "season_2023", "season_2024"]].replace({'True': True, 'False': False}).astype(int)

# Separar variables predictoras y objetivo
X = df.drop(columns=["monterrey_win"])  # predictoras
y = df["monterrey_win"]  # objetivo

# Revisar el dataset procesado
X

y

df.groupby("monterrey_win").size()

"""## Generación modelos"""

#División de datos en entrenamiento y prueba
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

print("X_train",X_train.shape)
print("X_test",X_test.shape)
print("y_train",y_train.shape)
print("y_test",y_test.shape)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

def evaluate_model(model, X_train, y_train, X_test, y_test):
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    y_train_pred = model.predict(X_train)

    n_train, k_train = X_train.shape
    n_test, k_test = X_test.shape

    accuracy_train = accuracy_score(y_train, y_train_pred)
    accuracy_test = accuracy_score(y_test,y_pred)


    print(f"Modelo: {model.__class__.__name__}")
    print(f"Accuracy en entrenamiento: {accuracy_train:.4f}")
    print(f"Accuracy en prueba: {accuracy_test:.4f} \n")

    return model

# Aplicar modelos sin hiperparámetros
rf = evaluate_model(RandomForestClassifier(random_state=0), X_train_scaled, y_train, X_test_scaled, y_test)
gb = evaluate_model(GradientBoostingClassifier(random_state=0), X_train_scaled, y_train, X_test_scaled, y_test)
dt = evaluate_model(DecisionTreeClassifier(random_state=0), X_train_scaled, y_train, X_test_scaled, y_test)
knn = evaluate_model(KNeighborsClassifier(), X_train_scaled, y_train, X_test_scaled, y_test)
mlp = evaluate_model(MLPClassifier(random_state=0, max_iter=1000), X_train_scaled, y_train, X_test_scaled, y_test)
lr = evaluate_model(LogisticRegression(random_state=0, max_iter=1000), X_train_scaled, y_train, X_test_scaled, y_test)

"""Podemos observar como los modelos se estan sobreajustando, vamos a probar. un ajuste de hiperparametros"""

def tune_model(model, param_grid, X_train, y_train, X_test, y_test):
    grid_search = RandomizedSearchCV(model, param_grid, n_iter=10, cv=5, scoring='accuracy', n_jobs=-1, random_state=0)
    grid_search.fit(X_train, y_train)

    best_model = grid_search.best_estimator_
    y_pred = best_model.predict(X_test)
    y_train_pred = best_model.predict(X_train)

    n_train, k_train = X_train.shape
    n_test, k_test = X_test.shape

    accuracy_train = accuracy_score(y_train, y_train_pred)
    accuracy_test = accuracy_score(y_test,y_pred)

    print(f"Modelo: {model.__class__.__name__}")
    print(f"Accuracy en entrenamiento: {accuracy_train:.4f}")
    print(f"Mejores parámetros: {grid_search.best_params_}")
    print(f"Accuracy en prueba: {accuracy_test:.4f} \n")

    return best_model

# Definición de hiperparámetros
rf_params = {'n_estimators': [50, 100, 200, 300], 'max_depth': [5, 10, 15],
             'min_samples_split': [5, 10, 15], 'min_samples_leaf': [2, 4, 6], 'bootstrap': [True, False]}

gb_params = {'n_estimators': [50, 100, 200], 'learning_rate': [0.01, 0.05, 0.1], 'max_depth': [3, 5, 7], 'subsample': [0.8, 1.0]}

dt_params = {'max_depth': [5, 10, 20, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4]}

knn_params = {'n_neighbors': [3, 5, 7, 10], 'weights': ['uniform', 'distance'], 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}

mlp_params = {'hidden_layer_sizes': [(50,), (100,), (50, 50)],   'activation': ['relu', 'tanh'],  'solver': ['adam', 'sgd'],  'alpha': [0.01, 0.1, 0.5],  'learning_rate': ['constant', 'adaptive'] }

lr_params = {'penalty': ['l1', 'l2'],  'C': [0.01, 0.1, 1, 10],  'solver': ['liblinear', 'lbfgs']}

# Aplicar ajuste de hiperparámetros
best_rf = tune_model(RandomForestClassifier(random_state=0), rf_params, X_train_scaled, y_train, X_test_scaled, y_test)
best_gb = tune_model(GradientBoostingClassifier(random_state=0), gb_params, X_train_scaled, y_train, X_test_scaled, y_test)
best_dt = tune_model(DecisionTreeClassifier(random_state=0), dt_params, X_train_scaled, y_train, X_test_scaled, y_test)
best_knn = tune_model(KNeighborsClassifier(), knn_params, X_train_scaled, y_train, X_test_scaled, y_test)
best_mlp = tune_model(MLPClassifier(max_iter=1000), mlp_params, X_train_scaled, y_train, X_test_scaled, y_test)
best_lr = tune_model(LogisticRegression(max_iter=1000),lr_params, X_train_scaled, y_train, X_test_scaled, y_test)

"""El ajuste de hiperparametros no funciono. Probemos con validación cruzada."""

rf = RandomForestClassifier(n_estimators=200, max_depth=5, min_samples_split=10, min_samples_leaf=5)
cv_scores = cross_val_score(rf, X_train, y_train, cv=5, scoring='accuracy')
print("Cross-validation accuracy:", cv_scores.mean())

gb = GradientBoostingClassifier(subsample= 0.8, n_estimators=200, max_depth=5, learning_rate =0.1)
cv_scores = cross_val_score(gb, X_train, y_train, cv=5, scoring='accuracy')
print("Cross-validation accuracy:", cv_scores.mean())

knn = KNeighborsClassifier(weights= "uniform", n_neighbors=3, algorithm = "kd_tree")
cv_scores = cross_val_score(knn, X_train_scaled, y_train, cv=5, scoring='accuracy')
print("Cross-validation accuracy:", cv_scores.mean())

mlp = MLPClassifier(hidden_layer_sizes=(50,), alpha=0.1, learning_rate='constant', max_iter=1000)
cv_scores = cross_val_score(mlp, X_train_scaled, y_train, cv=5, scoring='accuracy')
print("Cross-validation accuracy:", cv_scores.mean())